feat: error messages proxy when run without args
digita-ai/dgt-id-broker pull request #399
Opened 2022-07-07 12:18 UTC by LiamThys

2022-07-27 09:15 UTC, BelgianNoise submitted a review, later dismissed
Works fine for me

2022-08-09 07:22 UTC, lem-onade requested changes

2022-08-09 07:22 UTC, lem-onade commented on packages/dgt-id-proxy/lib/main.spec.ts
> -
I'm not sure these test should have been deleted @AbelVandenBriel, coverage was also lowered.

2022-08-12 12:59 UTC, BelgianNoise commented on packages/dgt-id-proxy/lib/main.spec.ts
> -
I added the first test back. Left out the second one as it is not relevant anymore since this PR.

2022-08-16 07:42 UTC, AbelVandenBriel approved these changes

2022-08-16 08:02 UTC, AbelVandenBriel approved these changes

2022-08-16 08:35 UTC, JasperVandenberghen approved these changes
Works fine.

One question: is it automatically translated to my Mac's language settings? Cause if not I don't see why it should contain dutch.

<img width="790" alt="image" src="https://user-images.githubusercontent.com/43341653/184835474-7d8486bb-fb7c-4747-abe5-54ff58fd7bd3.png">

2022-08-16 08:38 UTC, lem-onade commented
> One question: is it automatically translated to my Mac's language settings? Cause if not I don't see why it should contain dutch.

Yes, seems to use system language:
```
➜  dgt-id-proxy git:(feat/error-message-proxy-without-args) npm run start

> @digita-ai/dgt-id-proxy@0.19.9 start /Users/stijn/Documents/digita/dgt-id-broker/packages/dgt-id-proxy
> node ./bin/server.js

node ./dist/main.js [args]

Options:
      --version                      Show version number               [boolean]
  -c, --config                                                          [string]
  -C, --urlWebIdFactoryClaim                                            [string]
  -u, --proxyUri                     URL of the proxy        [string] [required]
  -U, --upstreamUri                  URL of the upstream server
                                                             [string] [required]
  -m, --mainModulePath                                                  [string]
  -o, --openidConfigurationFilePath  relative path to the OIDC configuration
                                                             [string] [required]
  -j, --jwksFilePath                 relative path to the JWKs
                                                             [string] [required]
  -r, --redirectUri                                                     [string]
  -i, --clientId                                                        [string]
  -s, --clientSecret                                                    [string]
  -P, --proxyTokenUrl                                                   [string]
  -L, --proxyClientUrl                                                  [string]
  -A, --auth0Api                                                        [string]
      --help                         Show help                         [boolean]

Missing required arguments: proxyUri, upstreamUri, openidConfigurationFilePath, jwksFilePath
```

is my output

2022-08-16 08:38 UTC, lem-onade approved these changes

2022-08-16 08:38 UTC, BelgianNoise commented
> One question: is it automatically translated to my Mac's language settings? Cause if not I don't see why it should contain dutch.

Guess so. Mine was in english.

2022-08-16 08:38 UTC, merged